import {
  Megaphone,
  BookOpen,
  Users,
  Globe,
  Heart,
  Shield,
  EyeOff,
  Star,
  Target,
  Zap,
  Award,
  Crown,
  Flame,
  Handshake,
  Church,
  Cross,
  Lightbulb,
  MessageCircle,
  Music,
  Send,
  TrendingUp,
  Compass,
  Flag,
  Gift,
  HandHeart,
  Layers,
  Map,
  Mic,
  Rocket,
  Sprout,
  Sun,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  megaphone: Megaphone,
  "book-open": BookOpen,
  users: Users,
  globe: Globe,
  heart: Heart,
  shield: Shield,
  "eye-off": EyeOff,
  star: Star,
  target: Target,
  zap: Zap,
  award: Award,
  crown: Crown,
  flame: Flame,
  handshake: Handshake,
  church: Church,
  cross: Cross,
  lightbulb: Lightbulb,
  "message-circle": MessageCircle,
  music: Music,
  send: Send,
  "trending-up": TrendingUp,
  compass: Compass,
  flag: Flag,
  gift: Gift,
  "hand-heart": HandHeart,
  layers: Layers,
  map: Map,
  mic: Mic,
  rocket: Rocket,
  sprout: Sprout,
  sun: Sun,
};

export const ICON_NAMES = Object.keys(ICON_MAP);
