/**
 * Returns the default footer Craft.js JSON subtree.
 * Node IDs are prefixed with "footer-" to avoid collisions with page content.
 */
export function buildDefaultFooterJson(): Record<string, unknown> {
  return {
    "footer-root": {
      type: { resolvedName: "CraftFooter" },
      isCanvas: true,
      props: {
        backgroundColor: "#0a1e38",
        padding: 48,
        width: 1200,
        minHeight: 100,
        borderTopColor: "rgba(255,255,255,0.1)",
        borderTopWidth: 1,
      },
      nodes: ["footer-main-row", "footer-divider", "footer-bottom-row"],
      linkedNodes: {},
      parent: "ROOT",
    },
    "footer-main-row": {
      type: { resolvedName: "CraftRow" },
      isCanvas: true,
      props: { gap: 48, alignItems: "flex-start", flexWrap: "wrap", padding: 0, backgroundColor: "transparent", minHeight: 60 },
      nodes: ["footer-col-brand", "footer-col-links", "footer-col-connect"],
      linkedNodes: {},
      parent: "footer-root",
    },
    "footer-col-brand": {
      type: { resolvedName: "CraftColumn" },
      isCanvas: true,
      props: { width: "40%", minWidth: 200, padding: 0, backgroundColor: "transparent", alignItems: "flex-start", justifyContent: "flex-start", gap: 16 },
      nodes: ["footer-brand-title", "footer-brand-desc", "footer-brand-social"],
      linkedNodes: {},
      parent: "footer-main-row",
    },
    "footer-brand-title": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: { text: "<p><strong>Billion Soul Harvest</strong></p>", fontSize: 22, color: "#ffffff", textAlign: "left", width: 400, height: 40 },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-brand",
    },
    "footer-brand-desc": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: {
        text: "<p>Uniting the global Church to catalyze the greatest harvest of souls in history — reaching 1 billion people with the Gospel by 2033.</p>",
        fontSize: 14,
        color: "#9ca3af",
        textAlign: "left",
        width: 400,
        height: 80,
      },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-brand",
    },
    "footer-brand-social": {
      type: { resolvedName: "CraftSocialLinks" },
      isCanvas: true,
      props: {
        links: [
          { platform: "facebook", url: "#" },
          { platform: "instagram", url: "#" },
          { platform: "x", url: "#" },
          { platform: "youtube", url: "#" },
        ],
        iconSize: 20,
        iconColor: "#9ca3af",
        gap: 16,
        alignment: "left",
      },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-brand",
    },
    "footer-col-links": {
      type: { resolvedName: "CraftColumn" },
      isCanvas: true,
      props: { width: "25%", minWidth: 150, padding: 0, backgroundColor: "transparent", alignItems: "flex-start", justifyContent: "flex-start", gap: 8 },
      nodes: ["footer-links-title", "footer-links-list"],
      linkedNodes: {},
      parent: "footer-main-row",
    },
    "footer-links-title": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: { text: "<p><strong>Quick Links</strong></p>", fontSize: 14, color: "#ffffff", textAlign: "left", width: 200, height: 30 },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-links",
    },
    "footer-links-list": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: {
        text: "<p>About BSH</p><p>Global Gatherings</p><p>2033 Vision</p><p>Partner With Us</p>",
        fontSize: 14,
        color: "#9ca3af",
        textAlign: "left",
        width: 200,
        height: 120,
      },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-links",
    },
    "footer-col-connect": {
      type: { resolvedName: "CraftColumn" },
      isCanvas: true,
      props: { width: "35%", minWidth: 200, padding: 0, backgroundColor: "transparent", alignItems: "flex-start", justifyContent: "flex-start", gap: 8 },
      nodes: ["footer-connect-title", "footer-connect-desc", "footer-connect-email"],
      linkedNodes: {},
      parent: "footer-main-row",
    },
    "footer-connect-title": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: { text: "<p><strong>Connect</strong></p>", fontSize: 14, color: "#ffffff", textAlign: "left", width: 300, height: 30 },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-connect",
    },
    "footer-connect-desc": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: {
        text: "<p>Have questions or want to partner with the movement? We'd love to hear from you.</p>",
        fontSize: 14,
        color: "#9ca3af",
        textAlign: "left",
        width: 300,
        height: 60,
      },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-connect",
    },
    "footer-connect-email": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: {
        text: '<p><a href="mailto:info@billionsoulharvest.org" style="color: #06b6d4;">info@billionsoulharvest.org</a></p>',
        fontSize: 14,
        color: "#06b6d4",
        textAlign: "left",
        width: 300,
        height: 30,
      },
      nodes: [],
      linkedNodes: {},
      parent: "footer-col-connect",
    },
    "footer-divider": {
      type: { resolvedName: "CraftDivider" },
      isCanvas: true,
      props: { color: "rgba(255,255,255,0.1)", thickness: 1, widthPercent: 100, marginY: 8 },
      nodes: [],
      linkedNodes: {},
      parent: "footer-root",
    },
    "footer-bottom-row": {
      type: { resolvedName: "CraftRow" },
      isCanvas: true,
      props: { gap: 16, alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", padding: 0, backgroundColor: "transparent", minHeight: 30 },
      nodes: ["footer-copyright", "footer-legal-links"],
      linkedNodes: {},
      parent: "footer-root",
    },
    "footer-copyright": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: {
        text: `<p>\u00a9 ${new Date().getFullYear()} Billion Soul Harvest. All rights reserved.</p>`,
        fontSize: 12,
        color: "#6b7280",
        textAlign: "left",
        width: 400,
        height: 24,
      },
      nodes: [],
      linkedNodes: {},
      parent: "footer-bottom-row",
    },
    "footer-legal-links": {
      type: { resolvedName: "CraftText" },
      isCanvas: true,
      props: {
        text: '<p><a href="/privacy" style="color: #6b7280;">Privacy Policy</a>  <a href="/terms" style="color: #6b7280;">Terms of Use</a>  <a href="/connect" style="color: #6b7280;">Contact</a></p>',
        fontSize: 12,
        color: "#6b7280",
        textAlign: "right",
        width: 400,
        height: 24,
      },
      nodes: [],
      linkedNodes: {},
      parent: "footer-bottom-row",
    },
  };
}
